version: "3.4"

services:

  api:
    build:
       context: .
       target: dev
    # image: docker.frafos.net/license-api:latest
    container_name: api-express
    environment:
      PORT: 4242
      # use redis container fqdn
      REDIS_ADDR: //redis:6379
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    user: 1000:1000
    # netwrok: host
    ports:
      - 4242:4242

  redis:
    # build:
    #   context: front
    #   target: prod
    image: redis
    # netwrok: host
    ports:
      - 6379:6379
