name: TestAndCover

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - '*'

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install && apt install gcov

    - name: Test and report cover
      run: |
        npm run coverage
        bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
      env:

        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
